language: php
notifications:
  email: false
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - 'nightly'
before_install:
  - travis_retry composer self-update
  - composer install
script: phpunit --bootstrap vendor/autoload.php tests
